/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesVenuesIdRouteImport } from './routes/venues/$venuesId'
import { Route as UserUsernameRouteImport } from './routes/user.$username'
import { Route as HotsHostIdRouteImport } from './routes/hots.$hostId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as CityCategoryRouteImport } from './routes/$city/$category'
import { Route as ArtistArtistIdRouteImport } from './routes/$artist/$artistId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenuesIdRoute = VenuesVenuesIdRouteImport.update({
  id: '/venues/$venuesId',
  path: '/venues/$venuesId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const HotsHostIdRoute = HotsHostIdRouteImport.update({
  id: '/hots/$hostId',
  path: '/hots/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCategoryRoute = CityCategoryRouteImport.update({
  id: '/$city/$category',
  path: '/$city/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistIdRoute = ArtistArtistIdRouteImport.update({
  id: '/$artist/$artistId',
  path: '/$artist/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/signup': typeof SignupRoute
  '/$artist/$artistId': typeof ArtistArtistIdRoute
  '/$city/$category': typeof CityCategoryRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/hots/$hostId': typeof HotsHostIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/venues/$venuesId': typeof VenuesVenuesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/signup': typeof SignupRoute
  '/$artist/$artistId': typeof ArtistArtistIdRoute
  '/$city/$category': typeof CityCategoryRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/hots/$hostId': typeof HotsHostIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/venues/$venuesId': typeof VenuesVenuesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/signup': typeof SignupRoute
  '/$artist/$artistId': typeof ArtistArtistIdRoute
  '/$city/$category': typeof CityCategoryRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/hots/$hostId': typeof HotsHostIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/venues/$venuesId': typeof VenuesVenuesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create'
    | '/signup'
    | '/$artist/$artistId'
    | '/$city/$category'
    | '/events/$eventId'
    | '/hots/$hostId'
    | '/user/$username'
    | '/venues/$venuesId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create'
    | '/signup'
    | '/$artist/$artistId'
    | '/$city/$category'
    | '/events/$eventId'
    | '/hots/$hostId'
    | '/user/$username'
    | '/venues/$venuesId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create'
    | '/signup'
    | '/$artist/$artistId'
    | '/$city/$category'
    | '/events/$eventId'
    | '/hots/$hostId'
    | '/user/$username'
    | '/venues/$venuesId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateRoute: typeof CreateRoute
  SignupRoute: typeof SignupRoute
  ArtistArtistIdRoute: typeof ArtistArtistIdRoute
  CityCategoryRoute: typeof CityCategoryRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  HotsHostIdRoute: typeof HotsHostIdRoute
  UserUsernameRoute: typeof UserUsernameRoute
  VenuesVenuesIdRoute: typeof VenuesVenuesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venuesId': {
      id: '/venues/$venuesId'
      path: '/venues/$venuesId'
      fullPath: '/venues/$venuesId'
      preLoaderRoute: typeof VenuesVenuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hots/$hostId': {
      id: '/hots/$hostId'
      path: '/hots/$hostId'
      fullPath: '/hots/$hostId'
      preLoaderRoute: typeof HotsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/$category': {
      id: '/$city/$category'
      path: '/$city/$category'
      fullPath: '/$city/$category'
      preLoaderRoute: typeof CityCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$artist/$artistId': {
      id: '/$artist/$artistId'
      path: '/$artist/$artistId'
      fullPath: '/$artist/$artistId'
      preLoaderRoute: typeof ArtistArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateRoute: CreateRoute,
  SignupRoute: SignupRoute,
  ArtistArtistIdRoute: ArtistArtistIdRoute,
  CityCategoryRoute: CityCategoryRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  HotsHostIdRoute: HotsHostIdRoute,
  UserUsernameRoute: UserUsernameRoute,
  VenuesVenuesIdRoute: VenuesVenuesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
